GET http://localhost:8000/students

###

GET http://localhost:8000/students/67ba384695239d06f2a037c2

###

POST http://localhost:8000/students
Content-Type: application/json 

{
    "name":"Walker Ryan3",
    "class":"DWA"
}

###

PATCH http://localhost:8000/students/67aca443531bc2347816aa50
Content-Type: application/json 

{
    "name":"New Name",
    "class":"New Class"
}
###

DELETE  http://localhost:8000/students/67ba384695239d06f2a037c2